connector_image: airbyte/source-ecforce:dev
test_strictness_level: low
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_ecforce/spec.yaml"

  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"

  discovery:
    tests:
      - config_path: "secrets/config.json"

  basic_read:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        empty_streams:
          - name: "customer_notes"
            bypass_reason: "Customer notes may not exist for all customers"
        validate_data_points: true
        validate_schema: true
        
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
